Attribute VB_Name = "Module1"
Global glbFerrSelec As Integer
Global glbLColor As Long
Global glbProxPonto As Integer
Global glbFileName As String
Global glbOpFil As Integer
Global glbMetodo As Integer
Global glbFiltro As Integer
Global glbStatus As Integer
Global glbTxt As String
Global x1 As Integer
Global y1 As Integer
Global x2 As Integer
Global y2 As Integer
Global x3 As Integer
Global y3 As Integer
Global glbTcolor As Long
Global glbBcolor As Long

